Repository Bumper-Dosi/Bumper-Dosi-Frontend, pull requests merged in 2022-06, with the labels that each got.

#4 Feat/1001 대기실 및 자동차 구현
  package-lock.json
  package.json
  public/models/Car/License.txt
  public/models/Car/suv.glb
  public/models/Car/wheelDefault.glb
  src/components/Logout/index.js
  src/components/Main/index.js
  src/components/WaitingRoom/WaitingRoom.js
  src/components/models/Car.js
  src/components/models/EndWall.js
  src/components/models/EnergyBar.js
  src/components/models/Light.js
  src/components/models/MainPlane.js
  src/components/models/Pillar.js
  src/components/models/Sphere.js
  src/components/models/Vehicle.js
  src/components/models/Wheel.js
  src/constants/style.js
  src/hooks/useShadowHelper.js
  src/utils/getRandomHex.js
  src/utils/useControls.js
Labels: enhancement

#6 feat/1004: 카운트다운 컴포넌트 구현
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/Countdown/index.js
  src/components/Main/index.js
  src/components/WaitingRoom/WaitingRoom.js
  src/components/models/Car.js
  src/components/models/EndWall.js
  src/components/models/MainPlane.js
  src/components/models/Vehicle.js
  src/components/models/Wheel.js
  src/constants/index.js
  src/constants/style.js
  src/constants/time.js
  src/index.js
  src/utils/getRandomHex.js
Labels: enhancement

#5 Feat/1000 친구리스트 구현
  package-lock.json
  src/App.js
  src/components/Countdown/index.js
  src/components/FriendList/index.js
  src/components/Logout/index.js
  src/components/Main/index.js
  src/components/WaitingRoom/WaitingRoom.js
  src/config/auth/logService.js
Labels: enhancement

#7 feat: 알람모달 구현
  public/models/Car/Wheel.glb
  src/components/AlarmModal/index.js
  src/components/models/Vehicle.js
  src/components/models/Wheel.js
  src/constants/time.js
Labels: enhancement

#10 feat/1006: 주차라인 geometry 구현
  package-lock.json
  src/components/Main/index.js
  src/components/WaitingRoom/index.js
  src/components/models/CancelTrigger.js
  src/components/models/GameRoom.js
  src/components/models/ParkingZone.js
  src/components/models/ReadyTrigger.js
  src/constants/index.js
  src/history.js
  src/index.js
Labels: enhancement

#13 Feat/1005: 대기실 socket.io 구현
  package-lock.json
  src/components/Main/index.js
  src/components/WaitingRoom/index.js
  src/components/models/OtherUserVehicle.js
  src/components/models/Vehicle.js
  src/hooks/useControls.js
  src/utils/getRandomNumber.js
Labels: enhancement

#15 feat/1013: 게임 모드 소켓 구현 완료
  package-lock.json
  src/App.js
  src/components/Main/index.js
  src/components/models/DesertPlane.js
  src/components/models/GameRoom.js
  src/components/models/ParkingZone.js
  src/components/models/Vehicle.js
Labels: enhancement

#16 Refactor/3001: 친구리스트 state 로직 정리 및 알람 띄우기 서버랑 연결, 채팅창 한글 에러, css 정리
  src/components/AlarmModal/index.js
  src/components/ChatRoom/index.js
  src/components/FriendList/index.js
  src/components/Main/index.js
  src/components/models/Vehicle.js
Labels: enhancement

#18 Feat/1012: 결과창 모달( MatchResultModal ) 구현 완료
  package-lock.json
  src/components/MatchResultModal/index.js
  src/constants/style.js
  src/constants/time.js
Labels: enhancement

#19 feat/1020: 대기실 오브젝트 추가 배치 완료
  src/components/WaitingRoom/index.js
Labels: enhancement

#20 Feat/1007,1015: 자동차구현 완료, 게임모드 구현 완료
  public/sounds/accelerate.mp3
  public/sounds/boost.mp3
  public/sounds/crash.mp3
  public/sounds/engine.mp3
  public/sounds/honk.mp3
  public/sounds/tire-brake.mp3
  src/App.js
  src/components/AlarmModal/index.js
  src/components/GameRoom/BackSVGGame.js
  src/components/GameRoom/index.js
  src/components/Main/index.js
  src/components/MatchResultModal/index.js
  src/components/TextBox/TextBox.js
  src/components/WaitingRoom/index.js
  src/components/models/BoostGuage.js
  src/components/models/Car.js
  src/components/models/DeadRing.js
  src/components/models/EndWall.js
  src/components/models/EnergyBar.js
  src/components/models/Light.js
  src/components/models/OtherUserCar.js
  src/components/models/OtherUserVehicle.js
  src/components/models/Vehicle.js
  src/constants/style.js
  src/effects/audio/Accelerate.js
  src/effects/audio/Engine.js
  src/effects/audio/Honk.js
  src/hooks/useControls.js
Labels: enhancement

#22 Fix/5000: 깃허브( LoginWithGithub ) 로그인 연동 구현 완료
  src/App.js
  src/components/Login/SVG/GithubSVG.js
  src/components/Login/index.js
  src/components/Logout/index.js
  src/components/WaitingRoom/index.js
  src/components/models/Car.js
  src/config/auth/logService.js
Labels: enhancement

#29 Fix/5004: 배포 후 코드 컨벤션 및 오브젝트 스타일 수정
  public/index.html
  src/components/Login/index.js
  src/components/Logout/index.js
  src/components/WaitingRoom/index.js
  src/components/models/Pillar.js
  src/components/models/PlaySign.js
  src/components/models/RepoSign.js
Labels: enhancement

#31 Fix/5003: 엔진소리 수정, 체력 0 됐을 때 리셋버튼 안되도록 수정
  src/App.js
  src/components/GameRoom/index.js
  src/components/WaitingRoom/index.js
  src/components/models/BoostGuage.js
  src/components/models/Car.js
  src/components/models/Vehicle.js
  src/effects/audio/BGM.js
  src/effects/audio/Engine.js
  src/effects/audio/Honk.js
Labels: bug

#33 Fix/5008: 채팅소켓 연결 url 수정
  src/components/ChatRoom/index.js
Labels: bug

#34 Feat/1026: 로딩화면 추가
  src/App.js
  src/components/GameRoom/index.js
  src/utils/getRandomHex.js
Labels: enhancement

#38 test: MatchResultModal 테스트 케이스 작성 완료
  src/components/MatchResultModal/MatchResultModal.test.js
Labels: test

#39 docs: README 작성 완료
  README.md
Labels: documentation

#41 Docs
  README.md
Labels: documentation
